# Generated by Django 3.2 on 2022-02-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_auto_20220218_1314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishListItem',
        ),
    ]
