# Generated by Django 3.2 on 2022-02-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20220212_1824'),
        ('profiles', '0002_alter_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wishlist_items',
            field=models.ManyToManyField(blank=True, related_name='items', to='products.Product'),
        ),
    ]
