# Generated by Django 3.2 on 2022-01-22 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='reviews',
        ),
    ]
